const PROFILE_CALLBACK = '1. 👤';

const LANG_CALLBACK = '2. 🇺🇦';

const LOOK_CALLBACK = '3. ⚡️';

const COOP_CALLBACK = '4. 💸';

const HELP_CALLBACK = '5. ❓';

const NEXT_PROFILE_CALLBACK = '➡️';

const TEXT_CALLBACK = '✉️';

const LEAVE_PROFILES_CALLBACK = '❌';

const AD_CALLBACK = '🔎';

const REPORT_CALLBACK = '❗️';

const CLEAR_LAST_YES_CALLBACK = '✅';

const CLEAR_LAST_NO_CALLBACK = '❌';

const UPDATE_PROFILE_CALLBACK = 'update-profile';

export {
  AD_CALLBACK,
  CLEAR_LAST_NO_CALLBACK,
  CLEAR_LAST_YES_CALLBACK,
  COOP_CALLBACK,
  HELP_CALLBACK,
  LANG_CALLBACK,
  LEAVE_PROFILES_CALLBACK,
  LOOK_CALLBACK,
  NEXT_PROFILE_CALLBACK,
  PROFILE_CALLBACK,
  REPORT_CALLBACK,
  TEXT_CALLBACK,
  UPDATE_PROFILE_CALLBACK,
};
