#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit ${1}

response=$(curl --data-binary @codecov.yml -s https://codecov.io/validate)

if echo $response | grep -q "Valid!"
then
  echo "codecov.yml is valid"
else 
  echo "codecov.yml is invalid"
  echo $response
  exit 1
fi

npm run format
